name: Tests

on:
  - push

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: |
      [${{matrix.os}}] OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        elixir: ['1.14.x']
        otp: ['25.x']
        os: ['ubuntu-20.04']

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}

    - name: Build cache
      uses: actions/cache@v2
      with:
        path: _build
        key: build-${{matrix.os}}-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles('lib/**/*.ex') }}
        restore-keys: |
          build-${{matrix.os}}-${{matrix.otp}}-${{matrix.elixir}}-

    - name: Deps cache
      uses: actions/cache@v1
      with:
        path: deps
        key: deps-${{matrix.os}}-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles('mix.lock') }}
        restore-keys: |
          deps-${{matrix.os}}-${{matrix.otp}}-${{matrix.elixir}}-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile test env
      run: mix compile
      env:
        MIX_ENV: test

    # - name: Run tests
    #   run: mix coveralls.github
    #   env:
    #     MIX_ENV: test
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
